name: PyTorch Image Build and Release

on:
  push:
    paths:
      - "official-templates/pytorch/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clear space to remove unused folders
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine if this is a production build
        id: build_type
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "is_production=true" >> $GITHUB_OUTPUT
          else
            echo "is_production=false" >> $GITHUB_OUTPUT
          fi

      - name: Set release tag for dev builds
        if: steps.build_type.outputs.is_production != 'true'
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF##refs/heads/} | sed 's/\//-/g')
          echo "RELEASE=dev-${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: official-templates/pytorch
          file: official-templates/pytorch/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pytorch:${{ env.RELEASE || 'latest' }}


